### ISSUE TITLE
Plugin throws an Exception on load in new IntelliJIdea2017.3

### ISSUE THREAD

**Issue by stokito** [stokito/IdeaSingletonInspection#6]
```
Short name 'Singleton' is not unique
class 'com.github.stokito.IdeaSingletonInspection.SingletonInspection' in PluginDescriptor[name='Singleton Inspection', classpath='C:\Users\sergey.ponomarev\.IntelliJIdea2017.3\config\plugins\IdeaSingletonInspection.jar']
and
class'com.siyeh.ig.classlayout.SingletonInspection' in PluginDescriptor[name='IDEA CORE', classpath='C:\Program Files\JetBrains\IntelliJ IDEA 173.2099.14\lib\resources.jar']
conflict
java.lang.Throwable: Short name 'Singleton' is not unique
class 'com.github.stokito.IdeaSingletonInspection.SingletonInspection' in PluginDescriptor[name='Singleton Inspection', classpath='C:\Users\sergey.ponomarev\.IntelliJIdea2017.3\config\plugins\IdeaSingletonInspection.jar']
and
class'com.siyeh.ig.classlayout.SingletonInspection' in PluginDescriptor[name='IDEA CORE', classpath='C:\Program Files\JetBrains\IntelliJ IDEA 173.2099.14\lib\resources.jar']
conflict
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:80)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:58)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:123)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:171)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:158)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aristotll** [comment]
Same error today.
Maybe changes the shortName in this line, to another to avoid the collision with intelli built in inspectionj.
https://github.com/stokito/IdeaSingletonInspection/blob/68f906840a4d7029e458b2a7237df9f5fd43f040/META-INF/plugin.xml#L23

**Comment by stokito** [comment]
I fixed and updated the plugin. Will be available soon.
